// AI Insight panel — uses Gemini (or OpenAI fallback) to explain why this title
// might appeal to the viewer. Renders nothing when AI is not configured, so it
// degrades gracefully on the static demo build.
import { useEffect, useState } from "react";
import { Sparkles, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { aiExplain, useAiStatus } from "@/lib/api";

interface Props {
  title: string;
  type: "movie" | "series";
  year?: string;
  overview?: string;
  genres?: string[];
}

export function AiInsightPanel({ title, type, year, overview }: Props) {
  const { data: status } = useAiStatus();
  const [text, setText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchExplain = async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await aiExplain(title, year, overview, type);
      if (!r) setError("AI is unavailable right now.");
      else setText(r);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  // Auto-fire once when panel mounts and AI is configured.
  useEffect(() => {
    if (status?.configured && !text && !loading && !error) {
      fetchExplain();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status?.configured]);

  if (!status?.configured) return null;

  return (
    <div className="space-y-3 rounded-xl border border-primary/20 bg-gradient-to-br from-primary/[0.06] via-transparent to-transparent p-5">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-bold uppercase tracking-[0.18em] text-primary flex items-center gap-2">
          <Sparkles className="w-4 h-4" />
          AI Insight
        </h3>
        {!loading && (
          <Button
            size="sm"
            variant="ghost"
            className="h-7 px-2"
            onClick={fetchExplain}
            data-testid="ai-explain-refresh"
          >
            <RefreshCw className="w-3.5 h-3.5" />
          </Button>
        )}
      </div>
      {loading ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
          {status.provider === "gemini" ? "Gemini is thinking…" : "Generating…"}
        </div>
      ) : error ? (
        <p className="text-sm text-rose-400/90">{error}</p>
      ) : (
        <p className="text-sm leading-relaxed text-foreground/85 whitespace-pre-line">
          {text}
        </p>
      )}
      <p className="text-[10px] uppercase tracking-wider text-muted-foreground/60">
        Generated by {status.provider === "gemini" ? "Gemini" : status.provider === "openai" ? "GPT" : "AI"} — may contain inaccuracies
      </p>
    </div>
  );
}
